# -*- coding: utf-8 -*-
"""scrapper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoXZwz5yijvZ2yUWDEKLr6AXK-FOe1x_
"""

import requests
import numpy as np
from bs4 import BeautifulSoup

def scrapper(imdbId):
    id = str(int(imdbId))
    n_zeroes = 7 - len(id)
    new_id = "0"*n_zeroes + id
    URL = f"https://www.imdb.com/title/tt{new_id}/"
    request_header = {'Content-Type': 'text/html; charset=UTF-8',
                      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0',
                      'Accept-Encoding': 'gzip, deflate, br'}
    response = requests.get(URL, headers=request_header)  # Filled in: requests.get
    soup = BeautifulSoup(response.text, 'html.parser')  # Filled in: BeautifulSoup
    imdb_rating = soup.find('span', attrs={'class': 'imdbRating star small'})  # Filled in: Finding the rating
    return imdb_rating.text if imdb_rating else np.nan